apiVersion: v1
kind: Service
metadata:
  name: svc-mvcmusicstore
  labels:
    product: mvcmusicstore
spec:
  selector:
    app: app-mvcmusicstore
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-mvcmusicstore
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-mvcmusicstore
    spec:
      containers:
      - image: psreleasedemo.azurecr.io/mvcmusicstore:__Build.BuildId__
        imagePullPolicy: IfNotPresent
        name: mvcmusicstore
        resources: {}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regsecret